
dict = {
    'eng': {
        // Index page
        'welcome-word': "Welcome",
        'welcome': "Welcome to the Flying Dutchman!",
        'thirsty': "Feeling thirsty, sailor?",
        'staff': "LOGIN STAFF",
        'vip': "LOGIN VIP",
        'contact': "CONTACT",
        'concept': "OUR CONCEPT",
        'history': "OUR HISTORY",
        'menu': "Menu",
        'click': "Click on the pirate!",

        //Owner page
        'yes' : "Yes",
        'no' : "No",
        'question' : "What do you want to do?",
        'revise' : "REVISE AMOUNTS",
        'refill' : "ORDER REFILL OF ITEMS",
        'add' : "ADD ITEM TO MENU",
        'remove' : "REMOVE FROM MENU",
        'name' : "Name",
        'stock' : "Stock",
        'onmenu' : "On Menu",
        'refill' : "Refill",
        'back-to-staff': "BACK TO STAFF PAGE",

        // VIP page
        'vip-menu-order-message': "New order, drag and drop items here!",
        'waiterButton': "CALL A WAITER",
        'vipOrder': "CREATE NEW ORDER",
        'item-quantity': "Input quantity",
        'VIP-clear-order': "CLEAR ORDER",
        'price-total': "ORDER SUM = ",
        'VIP-pay-order': "PAY ORDER", 
        'sort-by-string': "Sort by", 
        'maximum-string' : "Max",
        'minimum-string' : "Min",
        'varugrupp' : "Category",
        'sek' : "SEK",
        'incl-vat' : "incl. VAT",
        'alkoholhalt' : "alcohol content",
        'prisinklmoms' : "price",
        'cocktail' : "cocktail",
        'rom': "Rum",
        'öl': "Beer",
        'vin': "Wine",
        'whiskey': "Whiskey",
        'rött': ", red",
        'vitt': ", white",
        'ljust': ", light",
        'mörkt': ", dark",
        'flaska': "bottle",
        'glas': "glass",
        'shot': "shot",
        'pint': "tap",
        'storlek': "Serving",
        'undergrupp': "Subcategory",
        'Vatten': "Water",
        'ursprunglandnamn' : "Country of origin",
        'Sverige': "Sweden",
        'Italien': "Italy",
        'Spanien': "Spain",
        'Australien': "Australia",
        'Chile': "Chile",
        'Nya-Zeeland': "New Zealand",
        'Varierande-ursprung': "Varying",
        'Storbritannien': "Great Britain",
        'Trinidad': "Trinidad",
        'Dominikanska-Republiken': "Dominican Republic",
        'inh-notter': "❕ Contains nuts",
        'inh-gluten': "❕ Contains gluten",
        'inh-laktos': "❕ Contains lactose",
        'inh-tannin': "❕ Contains tannin",
        'inh-koscher': "✔️ koscher",
        'inh-ekologisk': "✔️ ecological",
        'payment-type': "How would you like to pay?",
        'table': "TABLE",
        'bar': "BAR",

        // Staff page
        'log-out':"LOG OUT",
        'create-order': "CREATE ORDER",
        'see-orders': "ALL ORDERS",
        'edit-order': "EDIT ORDER",
        'show-inventory': "INVENTORY",
        'staff-new-order-msg': "New order",
        'choose-order-msg': "All orders: ",
        'close': "CLOSE",
        'option-choose-order': "Choose order here",
        'warningButton':"NOTIFY SECURITY",
        'show-table-window': "TABLES",
        'option-choose-table': "Choose table here",
        'all-tables-msg':"ALL TABLES: ",
        'show-table-choice': "CHOSEN TABLE: ",
        'tab-close':"CLOSE",
        'label-name':"Name: ",
        'label-quantity':"Quantity: ",
        'label-table':"Table: ",
        'submit-order':"Submit",
        'new-order':"CREATE NEW ORDER",
        'staff-pay-order':"PAY",
        'staff-clear-order': "CLEAR",
        'staff-edit-order':"EDIT",
        'staff-placement':"SEATING: ",
        'bar-placement':"Bar",
        'table-placement':"Table ",
        'staff-new-order-info':"Remove item by subtracting the amount to remove",
        'add-item':"ADD ITEM",

        // 404 page
        'page-not-found' : "Page not found",
        'return-to-index' : "Return to index",
    },
    'swe': {
        // Index page
        'welcome-word': "Välkommen",
        'welcome': "Välkommen till The Flying Dutchman!",
        'thirsty': "Sjömanens törstsläckande drycker",
        'staff': "LOGIN PERSONAL",
        'vip': "LOGIN VIP",
        'contact': "KONTAKT",
        'concept': "VÅRT KONCEPT",
        'history': "VÅR HISTORIA",
        'menu': "Meny",
        'click': "Klicka på piraten!",

        //Owner page
        'yes' : "Ja",
        'no' : "Nej",
        'question' : "Vad vill du göra?",
        'revise' : "REVIDERA MÄNGDER",
        'refill' : "BESTÄLL PÅFYLLNING AV VAROR",
        'add' : "LÄGG TILL VARA TILL MENYN",
        'remove' : "TA BORT VARA FRÅN MENYN",
        'name' : "Namn",
        'stock' : "I lager",
        'onmenu' : "På Menyn",
        'refill' : "Fyll På",
        'back-to-staff': "TILLBAKA TILL STAFF-SIDAN",

        // VIP page
        'vip-menu-order-message': "Ny beställning, drag and drop hit!",
        'waiterButton': "KALLA EN KIPARE",
        'vipOrder': "GÖR NY BESTÄLLNING",
        'item-quantity': "Ange antalet",
        'VIP-clear-order': "TA BORT BESTÄLLNINGEN",
        'price-total': "SUMMA = ",
        'VIP-pay-order': "BETALA BESTÄLLNINGEN", 
        'sort-by-string': "Sortering",
        'maximum-string' : "Max",
        'minimum-string' : "Min",
        'varugrupp' : "Kategori",
        'sek' : "kr",
        'incl-vat' : "inkl. moms",
        'alkoholhalt' : "alkoholhalt",
        'prisinklmoms' : "pris",
        'cocktail' : "cocktail",
        'rom': "Rom",
        'öl': "Öl",
        'vin': "Vin",
        'whiskey': "Whiskey",
        'rött': ", rött",
        'vitt': ", vitt",
        'ljust': ", ljust",
        'mörkt': ", mörkt",
        'flaska': "flaska",
        'glas': "glas",
        'shot': "shot",
        'pint': "pint",
        'storlek': "Storlek",
        'undergrupp': "subkategori",
        'Vatten': "Vatten",
        'ursprunglandnamn' : "Ursprungsland",
        'Sverige': "Sverige",
        'Italien': "Italien",
        'Spanien': "Spanien",
        'Australien': "Australien",
        'Chile': "Chile",
        'Nya-Zeeland': "Nya Zeeland",
        'Varierande-ursprung': "Varierande ursprung",
        'Storbritannien': "Storbritannien",
        'Trinidad': "Trinidad",
        'Dominikanska-Republiken': "Dominikanska Republiken",
        'inh-notter': "❕ Innehåller nötter",
        'inh-gluten': "❕ Innehåller gluten",
        'inh-laktos': "❕ Innehåller laktos",
        'inh-tannin': "❕ Innehåller tannin",
        'inh-koscher': "✔️ koscher",
        'inh-ekologisk': "✔️ ekologisk",
        'payment-type': "Hur vill du betala?",
        'table': "BORD",
        'bar': "BAR",

        // Staff page
        'log-out':"LOGGA UT",
        'create-order': "SKAPA ORDER",
        'see-orders': "ALLA ORDRAR",
        'edit-order': "ÄNDRA ORDER",
        'show-inventory': "LAGER",
        'staff-new-order-msg': "Ny order",
        'choose-order-msg': "Alla ordrar: ",
        'close': "STÄNG",
        'option-choose-order': "Välj order här",
        'warningButton':"LARMA VAKT",
        'show-table-window': "BORD",
        'option-choose-table': "Välj bord här",
        'all-tables-msg':"ALLA BORD: ",
        'show-table-choice': "VALT BORD: ",
        'tab-close':"STÄNG",
        'label-name':"Namn: ",
        'label-quantity':"Antal: ",
        'label-table':"Bord: ",
        'Submit':"Skicka",
        'new-order':"SKAPA NY ORDER",
        'staff-pay-order':"BETALA",
        'staff-clear-order': "RENSA",
        'staff-edit-order':"ÄNDRA",
        'staff-placement':"PLACERING: ",
        'bar-placement':"Bar",
        'table-placement':"Bord ",
        'staff-new-order-info':"Ta bort en vara genom att subtrahera antalet",


        // 404 page
        'page-not-found' : "Sida ej funnen",
        'return-to-index' : "Återgå till index-sidan",
    },
    'slo': {
        // Index page
        'welcome-word': "Dobrodošli",
        'welcome': "Dobrodošli v The Flying Dutchman!",
        'thirsty': "Žejni mornar si lahko vse privošči!",
        'staff': "VPIS ZAPOSLENI",
        'vip': "VPIS VIP GOST",
        'contact': "KONTAKT",
        'concept': "NAŠ KONCEPT",
        'history': "NAŠ RAZVOJ",
        'menu': "Meni",
        'click': "Klikni na pirata!",

        //Owner page
        'yes' : "TODO",
        'no' : "TODO",
        'question' : "TODO",
        'opt1' : "TODO",
        'revise' : "TODO",
        'refill' : "TODO",
        'add' : "TODO",
        'remove' : "TODO",
        'stock' : "TODO",
        'onmenu' : "TODO",
        'refill' : "TODO",
        'back-to-staff': "NAZAJ NA STRAN OSEBJA",

        // VIP page
        'vip-menu-order-message': "Novo naročilo, povleci željeno pijačo sem!",
        'waiterButton': "POKLIČI NATAKARJA",
        'vipOrder': "NOVO NAROČILO",
        'VIP-clear-order': "ODSTRANI NAROČILO",
        'item-quantity': "Vnesi količino",
        'price-total': "SKUPNA CENA = ",
        'VIP-pay-order': "PLAČAJ NAROČILO", 
        'sort-by-string': "Razvrsti",
        'maximum-string' : "Največ",
        'minimum-string' : "Najmanj",
        'varugrupp' : "Kategorija",
        'sek' : "SEK",
        'incl-vat' : "vključuje DDV",
        'alkoholhalt' : "vsebnost alkohola",
        'prisinklmoms' : "cena",
        'cocktail' : "koktejl",
        'rom': "Rum",
        'öl': "Pivo",
        'vin': "Vino",
        'whiskey': "Viski",
        'rött': ", rdeča",
        'vitt': ", Bela",
        'ljust': ", svetloba",
        'mörkt': ", temno",
        'flaska': "steklenico",
        'glas': "steklo",
        'shot': "shot",
        'pint': "pinta",
        'storlek': "velikost",
        'undergrupp': "podskupina",
        'Vatten': "Vode",
        'ursprunglandnamn' : "Država izvora",
        'Sverige': "Švedska",
        'Italien': "Italija",
        'Spanien': "Španija",
        'Australien': "Avstralija",
        'Chile': "Čile",
        'Nya-Zeeland': "Nova Zelandija",
        'Varierande-ursprung': "Različen izvor",
        'Storbritannien': "Združeno kraljestvo",
        'Trinidad': "Trinidad",
        'Dominikanska-Republiken': "Dominikanska republika",
        'inh-notter': "❕ vsebuje oreščke",
        'inh-gluten': "❕ vsebuje gluten",
        'inh-laktos': "❕ vsebuje laktozo",
        'inh-tannin': "❕ vsebuje tannin",
        'inh-koscher': "✔️ košer",
        'inh-ekologisk': "✔️ ekološki",
        'payment-type': "Kako bi radi plačali?",
        'table': "MIZA",
        'bar': "BAR",

        // Staff page
        'log-out':"ODJAVA",
        'create-order': "USTVARI NAROČILO",
        'see-orders': "VSE NAROČILA",
        'edit-order': "UREDI NAROČILO",
        'show-inventory': "ZALOGA",
        'staff-new-order-msg': "Novo naročilo",
        'choose-order-msg': "Vsa naročila: ",
        'close': "ZAPRTO",
        'option-choose-order': "Tukaj izberite naročilo",
        'warningButton':"OBVESTITE VARNOST",
        'show-table-window': "TABELA",
        'option-choose-table': "Tukaj izberite mizo",
        'all-tables-msg':"VSE MIZE: ",
        'show-table-choice': "IZBRANA MIZA: ",
        'tab-close':"ZAPRTO",
        'label-name':"Ime: ",
        'label-quantity':"Količina: ",
        'label-table':"Tabela: ",
        'Submit':"Pošlji",
        'new-order':"USTVARI NOVO NAROČILO",
        'staff-pay-order':"PLAČAJ",
        'staff-clear-order': "JASNO",
        'staff-edit-order':"UREDI",
        'staff-placement':"SEDEŽ: ",
        'bar-placement':"Bar",
        'table-placement':"Tabela ",
        'staff-new-order-info':"Odstranite element tako, da odštejete znesek, ki ga želite odstraniti",

        // 404 page
        'page-not-found' : "Stran ni najdena",
        'return-to-index' : "Razveljavi",
    }
}
